### ISSUE TITLE
Template app updater doesn't work correctly

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/juli#7]
I updated from Juli 1.0 to 1.2 and my apps don't show any update available.
<img width="367" alt="screen shot 2018-03-28 at 5 22 43 pm" src="https://user-images.githubusercontent.com/157270/38063197-b0f670b0-32ac-11e8-9088-a5580238479d.png">
<img width="804" alt="screen shot 2018-03-28 at 5 22 49 pm" src="https://user-images.githubusercontent.com/157270/38063195-adf211e4-32ac-11e8-89fb-23ea830734c9.png">

Ok, no problem, I'll just uninstall/reinstall:

<img width="572" alt="screen shot 2018-03-28 at 5 23 46 pm" src="https://user-images.githubusercontent.com/157270/38063217-cb7dc348-32ac-11e8-9640-3621e28b7f41.png">
<img width="472" alt="screen shot 2018-03-28 at 5 24 04 pm" src="https://user-images.githubusercontent.com/157270/38063226-d5b3332a-32ac-11e8-86a5-ce3a73444578.png">

Nope, that didn't seem to work either...

**Comment by quanglam2807** [comment]
@swrobel Actually, there's no update. The updater doesn't work correctly. I'll fix it :)
