### ISSUE TITLE
CSS doesn't load correctly on certain websites

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/juli#70]
From Jacob:
Hey Quang.  I’ve been enjoying Juli, but a recent update has broken an “app” I’m using.  It appears that it’s not pulling in a CSS file.
Any ideas?  For the record, this is Zendesk chat.

![screen-shot-2018-07-31-15-45-47](https://user-images.githubusercontent.com/1548835/43618461-15bca164-968e-11e8-9844-3b24a61e17e9.png)

**Comment by quanglam2807** [comment]
@itshaadi That would be a different issue.

**Comment by itshaadi** [comment]
so can you give me any snippet or address that css injection should work? any environment flag that could help me trace the problem? i'm just trying to make sure before submitting a new issue.

**Comment by quanglam2807** [comment]
@itshaadi I just tested your CSS with 9Gag and it worked.

```
body {
background: red !important;
}
```

**Comment by oojacoboo** [comment]
Hey @quanglam2807 any ideas on this one?

**Comment by quanglam2807** [comment]
@oojacoboo I'll try to update the engine to electron@3.0.0 this weekend to see if it fixes this.

**Comment by oojacoboo** [comment]
@quanglam2807 awesome - let's hope so :)

**Comment by oojacoboo** [comment]
@quanglam2807 issue is now resolved with Juli engine 2.7.0.

**Comment by quanglam2807** [comment]
@quanglam2807 Thank you for letting me know!
